### ISSUE TITLE
Update documentation on AWS response promise

### ISSUE THREAD

**Issue by tuelsch** [tinify/tinify-nodejs#14]
The documentation does not mention that if a minified image is stored with AWS the AWS response promise is available with a call to `meta()` like:
```javascript
var source = tinify.fromFile("large.jpg");
source.store({
  // ...options
})
  .meta()
  .then((/* meta info? */) => {})
  .catch((err) => {});
```

I had to read the source to find this. Allthough it was easy, the documentation should mention the possibility.

**Comment by tinify-support** [comment]
Hi Tuelsch,

Thank you for your input, we will keep this in mind next time we
revisit the API documentation.

Happy compressing!

Kind regards,

Ellinor Bergman

We are always looking for ways to improve our products. Click
here ( https://insights.hotjar.com/s?siteId=648131&surveyId=28591 )  to give us your opinion (it will take less than 1 minute).

tinify/tinify-nodejs on October 30, 2017 at 2:38pm wrote:

The documentation does not mention that if a minified image is
stored with AWS the AWS response promise is available with a call
to meta() like:

var source = tinify.fromFile("large.jpg");
source.store({
// ...options
})
.meta()
.then((/* meta info? */) => {})
.catch((err) => {});
I had to read the source to find this. Allthough it was easy, the
documentation should mention the possibility.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
( https://github.com/tinify/tinify-nodejs/issues/14 ), or mute the
thread
