### ISSUE TITLE
Add CLI functionality

### ISSUE THREAD

**Issue by zanona** [tinify/tinify-nodejs#3]
hey guys, Tinify have been helping me for a long time now and I was really happy to found out that there was a NPM package for it. I was wondering that it could be a great idea to embed a command line interface to it so we can trigger `tinify *.png` the command straight from terminal.

Have you guys had any thoughts about it yet?

thanks and all the best

**Comment by middagj** [comment]
Hi Marcus, thanks for you comments. There are already a few Grunt tasks developed for this kind of use:
 https://github.com/marrone/grunt-tinypng and https://github.com/tommaton/grunt-tinypng-compression, hope this is already useful for you now.

We have thought about writing a console application, but don't want it to be include it in our clients. This is because we want to all the clients to be the same, and we don't want to write a cli for all languages.  Also writing a good, user friendly client program is a project of its own and can of course use this client as dependency.

**Comment by zanona** [comment]
Thanks for the feedback @middagj.
Hopefully as you mentioned, it should be ok for me to simply create wrapper CLI around the library you already provide and use it as dependency.

All the best
