### ISSUE TITLE
Cannot get quantity after performing a request compression

### ISSUE THREAD

**Issue by shenxxu720** [tinify/tinify-nodejs#46]
After I perform compression (tinify.fromFile()), the value of tinify.compressionCount is undefined. Can I get the quantity only in the callback of tinify.validate()?

**Comment by PabloPerezDeCiriza** [comment]
Hi shenxxu720,

The issue you are finding is because tinify.fromFile() is an asyncronous operation.  The output is undefined because tinify.compressionCount is being executed before tinify.fromFile() is completed. You can try something like this:

`const tinify = require("tinify");
tinify.key = "YOUR_API_KEY";

tinify.fromFile("panda.png").toFile("panda_compressed.png").then(() => {
    console.log("Compression count:", tinify.compressionCount);
});`
